### ISSUE TITLE
Customizing style

### ISSUE THREAD

**Issue by Kuzdo** [WadeShuler/yii2-members-system#1]
Hi!

Maybe I'm asking for something simple, but where I should customizing styles? I shouldn't touching vendor dir, but e.g. frontend/web/css/[custom.css/site.css] are before th adminLTE styles, so they are not good to use (I don't want put everywhere !important). I'm new in Yii2.

Regards.

**Comment by WadeShuler** [comment]
Sorry for the late reply. Create your own stylesheet in `/frontend/web/css/`. Then in your layout files, call it after the call to theirs.

Example:

    dmstr\web\AdminLteAsset::register($this);  <-- theirs
    frontend\assets\MyAssets::register($this);  <-- yours

Don't forget to add at the top: `use frontend\assets\MyAsset;` to include it

You could always hard code in the HTML in the layout if you needed to.
