### ISSUE TITLE
Signup and Login links on Navbar return 404 error

### ISSUE THREAD

**Issue by TMM21042** [WadeShuler/yii2-members-system#3]
### What is the issue?
Installed the system per instructions.  Installation is on Windows 10 for local development.  The "Out of the Box" URIs described in the README (Configuring section) return a 404 error.  But I get the correct site homepage after setting up VHOSTS as recommended.  The About and Contact links in the Navbar work.  But the Signup and Login links return a file not found error.  Specifically, the links throw a HTTP exception.  The last successful entry in the YII error log is:
15:18:10.206	trace	yii\web\Application::handleRequest	Route requested: 'frontend/site/signup'

I separately tried the Demo and the Development versions of the system to see if there would be a difference.  But both produced the same error.  

### Additional Information
Although Composer and Grunt installed their packages without error, I did have some NPM warning errors on installation:

C:\xampp\htdocs\yii2-members-system>npm install
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global node-gyp@3.6.0 should be installed with -g

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN grunt-typescript@0.8.0 requires a peer of grunt@~0.4.5 but none was installed.

| Q                | A
| ---------------- | ---
| Yii2 Version     | - 2.0.11.2
| Yii2 Marketing System Version | -
| PHP version      | - 5.6.24
| Operating system | - Windows 10, XAMPP

**Comment by WadeShuler** [comment]
Are you using sub-domains for frontend and backend apps, such as `users.yoursite.com` and `admin.yoursite.com`?

The config is either or, sub-domains or not, in order to get the `Signup` and `Login` links to point to the correct URL. It is tricky because it is linking from one app to another.

**Which Yii2 Members System version?** Look in the `package.json` file for the version number. I just want to ensure your on the latest version, as older versions it was broke because I hadn't gotten to it yet.

Please post your `xxx/config/main.php` for both `mainsite` and `frontend`.

PS: I haven't updated the demo yet. I think it will require a minor tweak due to it being on OpenShift and using Symbolic links to point to the `admin` and `users` sections. I just haven't had time to deal with OpenShift's unique needs.

---

That said, I have the links working on my end, though I am on Mac with XAMPP. Unless it is a difference between Windows and Mac, then we just need to iron out your configuration.

**Comment by TMM21042** [comment]
I am using subdomains.  I have them configured in the Windows 10 HOSTS file in Windows/System31/…, and in the VHOSTS file my XAMPP Apache server.  I followed the recommendations from your README file.  Because you mentioned the subdomains. I manually typed in the subdomain URLs for users and admin (e.g., user.yii2-members-system.dev) and I can reach the login page for both user and admin.  But I cannot reach the signup page with either subdomain.  This makes sense to me, and would seem to suggest the subdomains are set correctly and work.

 

This is my JSON file information: 

     "name": "yii2-members-system",

  "version": "2.0.5",

 

I have attached the two main.php config files.

 

Thanks for the prompt reply and attention to the issue.

**Comment by WadeShuler** [comment]
Sorry for the delay. I wasn't aware I had a message.. Somehow I missed it.

After looking at your configs, you haven't set it up for sub-domain use.

1) in `/common/config/bootstrap.php` - Edit the domains to match what you have configured in your VHOST. Looks like your using `yii2-members-system.dev` for testing this out, so you don't need to change this. If you were to use this on your own domain for real, then you would need to add in your real domains.

2) in `/mainsite/config/main.php` and `/frontend/config/main.php`, please read the comments in these config files closely. You will see a few comments like `// uncomment for sub-domain use` and `// comment out the following line for sub-domain use`. There are a few spots, so read it closely.

Then it should work :)

**Comment by TMM21042** [comment]
Thanks.  Those configuration settings were the issue.  I did not see them mentioned in the configuration area of the README, but should have known to look at the config directories anyway.  Glad you mention the bootstrap.php settings too, for when I move to a live domain/site  All is working now.  Nice work.

**Comment by WadeShuler** [comment]
I am glad you got it working. Sorry, I re-read the README and the config and bootstrap are not mentioned. I will get that added soon so thanks for bringing that to my attention.

Knocking out little things like this is what will straighten out the kinks 👍
